# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://alpacadata.github.io"
baseurl: ""

# Google tracking id
google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############

lang: "en"
author: "Alpaca data"
title: "{ Alpaca Data }"
description: "Blog and website of Alpaca Data, I turn unstructured data into crazy stuff."
keywords: "Alpaca, data, Fabric, AI, visualization, LLM,"
favicon: "/img/favicon.ico"
################
# Header layout#
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

quote: "What's up data?"
me-img: "/img/jetpacktocat.png"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

#######
# Blog #
########

post-preview-words: 96
paginate: 5
email-share: False
fb-share: False
twitter-share: False
linkedin-share: True
reddit-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "personal-jekyll-theme"

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "October 2025 - Today"
    description: "Here we are, in a time where robots might take over, but thankfully they only want to read my posts"
  - image: "/img/timeline/baracktocat.jpg"
    date: "1492"
    description: "The internet? Almost. Huh! Where did my boat go?"
  - image: "/img/timeline/fryfrozen.jpg"
    date: "3000 BC"
    description: "Humans invent Fire, and I invent.. a blog idea. It's basically the same : Spreading information but with fewer cave paintings"

# First image of the Timeline
timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "your@email.here"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

author_blurb_image: "/img/author.png"
author_blurb: |
  Hello! <br>
  Since 2018 I've started my adventure in the planet... of Data, starting as a Big Data Engineer in Hadoop, Linux, Spark, QA, ML
  and Tableau along other streaming tools.<br>
  In 2021 I moved into Analytics, becoming a Data Analyst with core skills from Data Engineering and a Senior Data Engineer,
  working in PowerBI, DevOps, Fabric, Azure, Databricks, Solution Architecture, AI, SQL Server, Project Management, and mentoring.<br>
  I've worked on many data migrations and my motto is "work smart, not hard". 
  I like to automate and accelerate processes for the whole team. I'm always asking myself "how can we do it better?". <br> 
  If I can save computing time or make things easier, which translates into good ROI, I'm the first to speak.<br>

  Achievement unlocked : <br>
  - Created >40 reports <br>
  - Achieved < 0.2% delta in data migration between semantic Models <br>
  - Managed and optimized table in 150 GB Dwh<br>
  In my free time I'm like Batman: Programmer by day, Artist by night. I like to play guitar and paint :)
##################
# Social Buttons #
##################

social:
  - icon: "linkedin-in"
    url: "https://www.linkedin.com"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
  Timeline: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
